name: kevell_care
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  

  # state management and dependency injections
  dartz: ^0.10.1
  dio: ^5.1.2
  get_it: ^7.6.0
  injectable: ^2.1.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.3
  mqtt_client: ^10.0.0
  flutter_svg: ^2.0.7
  syncfusion_flutter_datepicker: ^21.2.10
  sliver_tools: ^0.2.12
  
  lottie: ^2.5.0
  flutter_secure_storage: ^8.0.0
  internet_connection_checker_plus: ^1.0.1
  syncfusion_flutter_charts: ^21.2.10
  path_provider: ^2.1.0
  share: ^2.0.4
  pdf: ^3.10.4
  video_player: ^2.7.0
  chewie: ^1.7.0
  socket_io_client: ^2.0.3+1
  flutter_webrtc: ^0.9.41
  image_picker: ^1.0.4
  permission_handler: ^10.4.5
  image_cropper: ^4.0.1
  dotted_border: ^2.0.0+3

  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  sqflite: ^2.3.0




assets:
    - assets/images/
  # For vide call 

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  injectable_generator: ^2.1.5
  change_app_package_name: ^1.1.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  branding: assets/images/branding.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png
  branding_dark: assets/images/branding.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/othor/
    - assets/icons/profile/
    - assets/icons/bottom_navigtion/
    - assets/lottie/


  
